/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeModuleIdRouteImport } from './routes/practice.$moduleId'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as PracticeAssignmentAssignmentIdRouteImport } from './routes/practice.assignment.$assignmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeModuleIdRoute = PracticeModuleIdRouteImport.update({
  id: '/practice/$moduleId',
  path: '/practice/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAssignmentAssignmentIdRoute =
  PracticeAssignmentAssignmentIdRouteImport.update({
    id: '/practice/assignment/$assignmentId',
    path: '/practice/assignment/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/flags': typeof FlagsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/practice/$moduleId': typeof PracticeModuleIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/assignment/$assignmentId': typeof PracticeAssignmentAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/flags': typeof FlagsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/practice/$moduleId': typeof PracticeModuleIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/practice': typeof PracticeIndexRoute
  '/practice/assignment/$assignmentId': typeof PracticeAssignmentAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/flags': typeof FlagsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/practice/$moduleId': typeof PracticeModuleIdRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/practice/': typeof PracticeIndexRoute
  '/practice/assignment/$assignmentId': typeof PracticeAssignmentAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/flags'
    | '/login'
    | '/profile'
    | '/progress'
    | '/reports'
    | '/users'
    | '/practice/$moduleId'
    | '/result/$attemptId'
    | '/students/$id'
    | '/practice/'
    | '/practice/assignment/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/flags'
    | '/login'
    | '/profile'
    | '/progress'
    | '/reports'
    | '/users'
    | '/practice/$moduleId'
    | '/result/$attemptId'
    | '/students/$id'
    | '/practice'
    | '/practice/assignment/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/flags'
    | '/login'
    | '/profile'
    | '/progress'
    | '/reports'
    | '/users'
    | '/practice/$moduleId'
    | '/result/$attemptId'
    | '/students/$id'
    | '/practice/'
    | '/practice/assignment/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRoute
  FlagsRoute: typeof FlagsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  PracticeModuleIdRoute: typeof PracticeModuleIdRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  StudentsIdRoute: typeof StudentsIdRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  PracticeAssignmentAssignmentIdRoute: typeof PracticeAssignmentAssignmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$moduleId': {
      id: '/practice/$moduleId'
      path: '/practice/$moduleId'
      fullPath: '/practice/$moduleId'
      preLoaderRoute: typeof PracticeModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/assignment/$assignmentId': {
      id: '/practice/assignment/$assignmentId'
      path: '/practice/assignment/$assignmentId'
      fullPath: '/practice/assignment/$assignmentId'
      preLoaderRoute: typeof PracticeAssignmentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRoute,
  FlagsRoute: FlagsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  PracticeModuleIdRoute: PracticeModuleIdRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  StudentsIdRoute: StudentsIdRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  PracticeAssignmentAssignmentIdRoute: PracticeAssignmentAssignmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
